/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Bike {
  'engineSpecs' : EngineSpecs,
  'name' : string,
  'category' : string,
  'brand' : string,
  'rating' : bigint,
  'price' : PriceRange,
  'photoId' : string,
}
export interface Brand { 'url' : string, 'name' : string }
export interface EngineSpecs {
  'displacement' : bigint,
  'emissionType' : string,
  'maxPower' : string,
  'coolingSystem' : string,
  'transmission' : string,
  'fuelSupplyType' : string,
  'engineType' : string,
}
export interface PriceRange { 'priceMax' : bigint, 'priceMin' : bigint }
export interface _SERVICE {
  'addBike' : ActorMethod<[Bike], bigint>,
  'addBrand' : ActorMethod<[Brand], bigint>,
  'getAllBikes' : ActorMethod<[], Array<Bike>>,
  'getAllBrands' : ActorMethod<[], Array<Brand>>,
  'getBike' : ActorMethod<[bigint], [] | [Bike]>,
  'getBikesByBrand' : ActorMethod<[string], Array<Bike>>,
  'getBikesByCategory' : ActorMethod<[string], Array<Bike>>,
  'getBikesByPriceRange' : ActorMethod<[bigint, bigint], Array<Bike>>,
  'getBrand' : ActorMethod<[bigint], [] | [Brand]>,
  'getCategories' : ActorMethod<[], Array<string>>,
  'getFeaturedBikes' : ActorMethod<[], Array<Bike>>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];