/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const EngineSpecs = IDL.Record({
  'displacement' : IDL.Nat,
  'emissionType' : IDL.Text,
  'maxPower' : IDL.Text,
  'coolingSystem' : IDL.Text,
  'transmission' : IDL.Text,
  'fuelSupplyType' : IDL.Text,
  'engineType' : IDL.Text,
});
export const PriceRange = IDL.Record({
  'priceMax' : IDL.Nat,
  'priceMin' : IDL.Nat,
});
export const Bike = IDL.Record({
  'engineSpecs' : EngineSpecs,
  'name' : IDL.Text,
  'category' : IDL.Text,
  'brand' : IDL.Text,
  'rating' : IDL.Nat,
  'price' : PriceRange,
  'photoId' : IDL.Text,
});
export const Brand = IDL.Record({ 'url' : IDL.Text, 'name' : IDL.Text });

export const idlService = IDL.Service({
  'addBike' : IDL.Func([Bike], [IDL.Nat], []),
  'addBrand' : IDL.Func([Brand], [IDL.Nat], []),
  'getAllBikes' : IDL.Func([], [IDL.Vec(Bike)], ['query']),
  'getAllBrands' : IDL.Func([], [IDL.Vec(Brand)], ['query']),
  'getBike' : IDL.Func([IDL.Nat], [IDL.Opt(Bike)], ['query']),
  'getBikesByBrand' : IDL.Func([IDL.Text], [IDL.Vec(Bike)], ['query']),
  'getBikesByCategory' : IDL.Func([IDL.Text], [IDL.Vec(Bike)], ['query']),
  'getBikesByPriceRange' : IDL.Func(
      [IDL.Nat, IDL.Nat],
      [IDL.Vec(Bike)],
      ['query'],
    ),
  'getBrand' : IDL.Func([IDL.Nat], [IDL.Opt(Brand)], ['query']),
  'getCategories' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  'getFeaturedBikes' : IDL.Func([], [IDL.Vec(Bike)], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const EngineSpecs = IDL.Record({
    'displacement' : IDL.Nat,
    'emissionType' : IDL.Text,
    'maxPower' : IDL.Text,
    'coolingSystem' : IDL.Text,
    'transmission' : IDL.Text,
    'fuelSupplyType' : IDL.Text,
    'engineType' : IDL.Text,
  });
  const PriceRange = IDL.Record({ 'priceMax' : IDL.Nat, 'priceMin' : IDL.Nat });
  const Bike = IDL.Record({
    'engineSpecs' : EngineSpecs,
    'name' : IDL.Text,
    'category' : IDL.Text,
    'brand' : IDL.Text,
    'rating' : IDL.Nat,
    'price' : PriceRange,
    'photoId' : IDL.Text,
  });
  const Brand = IDL.Record({ 'url' : IDL.Text, 'name' : IDL.Text });
  
  return IDL.Service({
    'addBike' : IDL.Func([Bike], [IDL.Nat], []),
    'addBrand' : IDL.Func([Brand], [IDL.Nat], []),
    'getAllBikes' : IDL.Func([], [IDL.Vec(Bike)], ['query']),
    'getAllBrands' : IDL.Func([], [IDL.Vec(Brand)], ['query']),
    'getBike' : IDL.Func([IDL.Nat], [IDL.Opt(Bike)], ['query']),
    'getBikesByBrand' : IDL.Func([IDL.Text], [IDL.Vec(Bike)], ['query']),
    'getBikesByCategory' : IDL.Func([IDL.Text], [IDL.Vec(Bike)], ['query']),
    'getBikesByPriceRange' : IDL.Func(
        [IDL.Nat, IDL.Nat],
        [IDL.Vec(Bike)],
        ['query'],
      ),
    'getBrand' : IDL.Func([IDL.Nat], [IDL.Opt(Brand)], ['query']),
    'getCategories' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
    'getFeaturedBikes' : IDL.Func([], [IDL.Vec(Bike)], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };