/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface PriceRange {
    priceMax: bigint;
    priceMin: bigint;
}
export interface EngineSpecs {
    displacement: bigint;
    emissionType: string;
    maxPower: string;
    coolingSystem: string;
    transmission: string;
    fuelSupplyType: string;
    engineType: string;
}
export interface Brand {
    url: string;
    name: string;
}
export interface Bike {
    engineSpecs: EngineSpecs;
    name: string;
    category: string;
    brand: string;
    rating: bigint;
    price: PriceRange;
    photoId: string;
}
export interface Lead {
    id: bigint;
    name: string;
    phone: string;
    city: string;
    bikeName: string;
    formType: string;
    timestamp: bigint;
}
export interface backendInterface {
    addBike(bike: Bike): Promise<bigint>;
    addBrand(brand: Brand): Promise<bigint>;
    getAllBikes(): Promise<Array<Bike>>;
    getAllBrands(): Promise<Array<Brand>>;
    getBike(bikeId: bigint): Promise<Bike | null>;
    getBikesByBrand(brandName: string): Promise<Array<Bike>>;
    getBikesByCategory(category: string): Promise<Array<Bike>>;
    getBikesByPriceRange(minPrice: bigint, maxPrice: bigint): Promise<Array<Bike>>;
    getBrand(brandId: bigint): Promise<Brand | null>;
    getCategories(): Promise<Array<string>>;
    getFeaturedBikes(): Promise<Array<Bike>>;
    _initializeAccessControlWithSecret(secret: string): Promise<void>;
    submitLead(name: string, phone: string, city: string, bikeName: string, formType: string): Promise<bigint>;
    getLeads(): Promise<Array<Lead>>;
}
import type { Bike as _Bike, Brand as _Brand } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async addBike(arg0: Bike): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addBike(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addBike(arg0);
            return result;
        }
    }
    async addBrand(arg0: Brand): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addBrand(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addBrand(arg0);
            return result;
        }
    }
    async getAllBikes(): Promise<Array<Bike>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllBikes();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllBikes();
            return result;
        }
    }
    async getAllBrands(): Promise<Array<Brand>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllBrands();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllBrands();
            return result;
        }
    }
    async getBike(arg0: bigint): Promise<Bike | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getBike(arg0);
                return from_candid_opt_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBike(arg0);
            return from_candid_opt_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async getBikesByBrand(arg0: string): Promise<Array<Bike>> {
        if (this.processError) {
            try {
                const result = await this.actor.getBikesByBrand(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBikesByBrand(arg0);
            return result;
        }
    }
    async getBikesByCategory(arg0: string): Promise<Array<Bike>> {
        if (this.processError) {
            try {
                const result = await this.actor.getBikesByCategory(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBikesByCategory(arg0);
            return result;
        }
    }
    async getBikesByPriceRange(arg0: bigint, arg1: bigint): Promise<Array<Bike>> {
        if (this.processError) {
            try {
                const result = await this.actor.getBikesByPriceRange(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBikesByPriceRange(arg0, arg1);
            return result;
        }
    }
    async getBrand(arg0: bigint): Promise<Brand | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getBrand(arg0);
                return from_candid_opt_n2(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBrand(arg0);
            return from_candid_opt_n2(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCategories(): Promise<Array<string>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCategories();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCategories();
            return result;
        }
    }
    async getFeaturedBikes(): Promise<Array<Bike>> {
        if (this.processError) {
            try {
                const result = await this.actor.getFeaturedBikes();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFeaturedBikes();
            return result;
        }
    }
    async _initializeAccessControlWithSecret(_secret: string): Promise<void> {
        return Promise.resolve();
    }
    async submitLead(name: string, phone: string, city: string, bikeName: string, formType: string): Promise<bigint> {
        const result = await (this.actor as any).submitLead(name, phone, city, bikeName, formType);
        return result;
    }
    async getLeads(): Promise<Array<Lead>> {
        const result = await (this.actor as any).getLeads();
        return result;
    }
}
function from_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Bike]): Bike | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Brand]): Brand | null {
    return value.length === 0 ? null : value[0];
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
